### ISSUE TITLE
Change /admin/addproduct to /dashboard

### ISSUE THREAD

**Issue by vladstanescu94** [vladstanescu94/ProiectIS#45]

**Comment by precupstefan** [comment]
@adrianbunea , incearca sa faci tu issue asta, cred ca o sa iti clarifice o gramada din chestiile care se intampla in proiect

**Comment by adrianbunea** [comment]
> @adrianbunea , incearca sa faci tu issue asta, cred ca o sa iti clarifice o gramada din chestiile care se intampla in proiect

Da ce are?

**Comment by precupstefan** [comment]
nu are nimica, dar daca intelegi logica la chestia asta, intelegi logica pentru cea mai mare parte a proiectului
